# Code generated by ChatGPT


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib

# 데이터 로드
file_path = '202406_202406_연령별인구현황_월간.csv'
data = pd.read_csv(file_path, encoding='euc-kr')

# 지역 선택
st.title("특정 연령 인구 비율")
selected_region = st.selectbox('지역을 선택하세요:', data['행정구역'].unique())
selected_age = st.text_input('나이를 입력하세요(숫자만):')
ages = ['2024년06월_계_' + selected_age + '세']

# 선택한 지역의 데이터 추출
region_data = data[data['행정구역'] == selected_region]

# 해당 연령 인구수
population = region_data[ages].apply(lambda x: x.str.replace(',', '').astype(int)).sum(axis=1).values[0]

# 총 인구수
total_population = int(region_data['2024년06월_계_총인구수'].str.replace(',', '').values[0])

# 비율 계산
ratio = (population / total_population) * 100

# 원 그래프 생성
labels = ['해당 연령대', '기타 연령대']
sizes = [ratio, 100 - ratio]
colors = ['#ff9999','#66b3ff']
explode = (0.1, 0)

fig1, ax1 = plt.subplots()
ax1.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',
        shadow=True, startangle=140)
ax1.axis('equal')

# 그래프 출력
st.pyplot(fig1)
